ITIMER_PROF = ITIMER_REAL = ITIMER_VIRTUAL = ItimerError = NSIG = SIGABRT = SIGALRM = SIGBUS = SIGCHLD = SIGCLD = None
SIGCONT = SIGFPE = SIGHUP = SIGILL = SIGINT = SIGIO = SIGIOT = SIGKILL = SIGPIPE = SIGPOLL = SIGPROF = SIGPWR = None
SIGQUIT = SIGRTMAX = SIGRTMIN = SIGSEGV = SIGSTOP = SIGSYS = SIGTERM = SIGTRAP = SIGTSTP = SIGTTIN = SIGTTOU = None
SIGURG = SIGUSR1 = SIGUSR2 = SIGVTALRM = SIGWINCH = SIGXCPU = SIGXFSZ = SIG_DFL = SIG_IGN = None


def signal(*args):
    return None

def siginterrupt(*args):
    return None